version: '3.4'

services:
  redis:
    image: redis:7.0
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - type: volume
        source: typi-ultra-redis-data
        target: /data
volumes:
  typi-ultra-redis-data: