version: '3.4'

services:
  redis:
    image: redis:7.0
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - type: volume
        source: typi-ultra-redis-data
        target: /data
  wa-otp:
    image: registry.gitlab.com/kaspi-cabinet/cabin-backend/wa-image:kuber
    restart: on-failure
    environment:
      QUEUE: 'wa-otp'
    volumes:
      - ./data/wa-otp/session:/usr/src/app/wa-broadcast/.wwebjs_auth/session
    expose:
      - "8888"
volumes:
  typi-ultra-redis-data: